### PR TITLE
Added visibleFirstDay KVO-observable property

### PR DESCRIPTION
**Pull request by zsszatmari**
Hi, please accept pull request.

### CODE REVIEW

**Comment by ruslanskorb** [comment]
@zsszatmari Hey! What is the purpose of this property?

**Comment by zsszatmari** [comment]
Hi! I needed a way to display the currently visible month outside the RSDFDatePickerView itself, as I scroll up-down. (for our UI design we don't use the month header)

**Comment by ruslanskorb** [comment]
@zsszatmari Probably, it is your case - https://github.com/ruslanskorb/RSDayFlow/issues/126.

**Comment by zsszatmari** [comment]
Well, yes, that would probably also work.

**Pull request closed without merging**
