### PR TITLE
Feature/customize past date label

### PR DESCRIPTION
**Pull request by thonydam**
Add capability to customize past day label text color.

### CODE REVIEW

**Comment by ruslanskorb** [comment]
Hi @thonydam!
Thanks for the PR!
I think that we do not need the individual color for the day off. Can we remove it?
And we should not compare the current date to the date of the cell twice. It is better to do it once, store the result in a variable and use it.

**Comment by thonydam** [comment]
Hi @ruslanskorb ,

Thanks for the quick review!

If you want to keep the weekend days with a customizable text color, I think we need to have the individual color for the past day off.

**Comment by ruslanskorb** [comment]
Okay, we can save the individual color for the past day off. But one more thing. I would not want to change the default color for the past days.

**Comment by thonydam** [comment]
I set the past day default color to the day color.

**Comment by ruslanskorb** [comment]
:thumbsup:

**Pull request merged**
