### PR TITLE
Added "overloaded" reload function that includes a completion block.

### PR DESCRIPTION
**Pull request by MortenHN81**
I was in a situation where i needed to select a data after the collectionview did finished load. As the collectionview was not public i decided to make a new reload function that take a block as parameter. This block is called when the collectionview is finished loading. This could also be used if you would like to utilize a spinner that you want to remove after load is finished.

My first solution was to just return the collectionview in the current reload function. But as it was already private it seemed like a poor solution. So i decided to add a new function to keep it clean.

I have implemented this solution in my own project, and it works fine.

Im not 100% sure if there was any other way in the current project to achieve this, but i was not able to find one.

thank for a awesome component that i love to use!

### CODE REVIEW

**Comment by ruslanskorb** [comment]
Sorry, but I really can't understand what are you trying to achieve. What exactly are you trying to do? Could you give an example?

**Comment by MortenHN81** [comment]
Hi, Thank you for getting back to me.

I prefetch som data from a API, that defines if there should be a mark on the specifik day. The data from the api is cache in a interval. When im scrolling in the calendar and run of of cache im requesting a new batch of data while im doing this a spinner is shown. 
When the request is finished i call reload. When the request from the API is finished i may need to select a specifik date specified by the API. In my call back from the API i cant both reload the DayFlowView and set a selected day. If i set the selected day, it will be overridden by the reload and remove the selected marking. Thats why i need the callback when the reload is finished to select a day when DayFlow has finished loading and shouldmark is no longer called. Im archiving this with this current pull request. Im already running the modified reload in my project and it works as expected. my only problem is that next time you send out and update that i want, it will override my change in the pod, thats why i took the chance and made this pull request :)

Thank you for listening, hope this makes it more clear. If this is already possible in some way, i have not been able to find where in the docs or code i can how to do this. But if so i apologize.

**Comment by ruslanskorb** [comment]
You need to call `selectDate:`  method after calling `reloadData` method.

```obj-c
[self.datePickerView reloadData];
[self.datePickerView selectDate:[NSDate date]];
```

**Comment by MortenHN81** [comment]
What i experienced was that i call reload, and selecteddate imidlertid after, like you describe. I see the selected date, after the API call is finished i call reload and selecteddate again, and the selectedday disappear when the selecteddate cell is reloaded. After adding the call back to the reload and first setting the date after the reload is complete this problem did no longer persist. 
Please if you do not want this addition then cancel it and ill just keep using my own branch of the RSDayFlow. I just thought that if it was usefull to me, then it could also be usefull to others :)

**Comment by MortenHN81** [comment]
Saw that i could close it my self ;) ill just keep running my own branch. Thank you again for your great work on this component.

**Pull request closed without merging**
